MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/RegistroVisitas/EditarRegistroVisita.cshtml.cs
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MascotaFeliz.App.Frontend.Pages {
    public class EditarRegistroVisitaModel : PageModel {
        private readonly IRepositorioRegistroVisita _repoRegistroVisita;
        
        [BindProperty]
        public RegistroVisita RegistroVisita { get; set;} 

        public EditarRegistroVisitaModel (IRepositorioRegistroVisita repoRegistroVisita) {
            this._repoRegistroVisita = repoRegistroVisita;
        }
        
        public IActionResult OnGet(int id) {
            RegistroVisita = _repoRegistroVisita.GetRegistroVisita(id);
                return Page();
        }

        public IActionResult OnPost() {
            RegistroVisita = _repoRegistroVisita.UpdateRegistroVisita(RegistroVisita);
            return RedirectToPage("./ListaRegistroVisita");
        }
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/RegistroVisitas/ListaRegistroVisita.cshtml.cs
using System.Collections.Generic;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace MascotaFeliz.App.Frontend.Pages {

    [Authorize]
    public class ListaRegistroVisitaModel : PageModel {

    private readonly IRepositorioRegistroVisita _repoRegistroVisita;
    public IEnumerable<RegistroVisita> RegistrosVisitas { get; set;}
    [BindProperty]
    public RegistroVisita RegistroVisita { get; set;} 

    public ListaRegistroVisitaModel (IRepositorioRegistroVisita repoRegistroVisita) {
        _repoRegistroVisita = repoRegistroVisita;
    }

        public void OnGet() {
            RegistrosVisitas = listarRegistrosVisitas();
        }

        public ActionResult OnPost() {
            if(!ModelState.IsValid) {
                return RedirectToPage("ListaPropietario");
            }
            AddRegistroVisita();
            return RedirectToPage("ListaRegistroVisita");
        }

        public IEnumerable<RegistroVisita> listarRegistrosVisitas() {
            IEnumerable<RegistroVisita> RegistrosVisitas = _repoRegistroVisita.GetAllRegistroVisitas();
            return RegistrosVisitas;
        }

        private void AddRegistroVisita () {

            _repoRegistroVisita.AddRegistroVisita(new RegistroVisita {
                MascotaId = RegistroVisita.MascotaId,
                TarjetaProfesionalVeterinario = RegistroVisita.TarjetaProfesionalVeterinario,
                FechaHora = RegistroVisita.FechaHora,
                Temperatura = RegistroVisita.Temperatura,
                Peso = RegistroVisita.Peso,
                FrecuenciaRespiratoria = RegistroVisita.FrecuenciaRespiratoria,
                FrecuenciaCardiaca = RegistroVisita.FrecuenciaCardiaca,
                EstadoAnimo = RegistroVisita.EstadoAnimo,
                Medicamentos = RegistroVisita.Medicamentos,
                Recomendaciones = RegistroVisita.Recomendaciones     
            });
        }

        public IActionResult OnGetDeleteRegistroVisita(int Id) {
            _repoRegistroVisita.DeleteRegistroVisita(Id);
            return Redirect("ListaRegistroVisita");
        }
    
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/RegistroVisitas/EditarRegistroVisita.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.EditarRegistroVisitaModel
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Formulario para la modificación del registro de visitas</title>
    @* <link rel="stylesheet" href="~/css/propietarios.css" /> *@
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="contenedor">
    <header class="header">
        <h1 id="title" class="text-center">Actualización del registro de visitas</h1>
        <p id="description" class="description text-center">Modifica el registro de la visita aquí.</p>
    </header>

    <form method="post" class="grid2-form">
        <input asp-for="RegistroVisita.Id" type="hidden"/>
        
        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.MascotaId" class="control-label">Id de la Mascota</label>
            <input type="number" asp-for="RegistroVisita.MascotaId" id="MascotaId" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.TarjetaProfesionalVeterinario" class="control-label">Veterinario</label>
            <input type="number" asp-for="RegistroVisita.TarjetaProfesionalVeterinario" id="TarjetaProfesionalVeterinario" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FechaHora" class="control-label">Fecha de la visita</label>
            <input type="date" asp-for="RegistroVisita.FechaHora" id="FechaHora" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Temperatura" class="control-label">Temperatura</label>
            <input type="number" asp-for="RegistroVisita.Temperatura" id="Temperatura" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Peso" class="control-label">Peso</label>
            <input type="number" asp-for="RegistroVisita.Peso" id="Peso" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FrecuenciaRespiratoria" class="control-label">Frecuencia Respiratoria</label>
            <input type="text" asp-for="RegistroVisita.FrecuenciaRespiratoria" id="FrecuenciaRespiratoria" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FrecuenciaCardiaca" class="control-label">Frecuencia Cardiaca</label>
            <input type="text" asp-for="RegistroVisita.FrecuenciaCardiaca" id="FrecuenciaCardiaca" class="form-control">
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.EstadoAnimo" class="control-label">Estado de ánimo</label>
            <select type="text" asp-for="RegistroVisita.EstadoAnimo" id="EstadoAnimo" class="form-control" required="">
                <option disabled="" value="">Seleccione el estado de ánimo</option>
                <option value="0">Tranquilo</option>
                <option value="1">Hiperactivo</option>
                <option value="2">Asustado</option>
                <option value="3">Nervioso</option>
                <option value="4">Agresivo</option>
                <option value="5">Triste</option>
                <option value="6">Aislado</option>
                <option value="7">Sin apetito</option>
                <option value="8">Ansioso</option>
                <option value="9">Deprimido</option>
            </select>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Medicamentos" class="control-label">Medicamentos</label>
            <input type="text" asp-for="RegistroVisita.Medicamentos" id="Medicamentos" class="form-control">
        </div>

        <div class="form-group-full">
            <label id="label" asp-for="RegistroVisita.Recomendaciones" class="control-label">Recomendaciones</label>
            <textarea type="text-area" asp-for="RegistroVisita.Recomendaciones" id="Recomendaciones" class="input-textarea">
                </textarea>
        </div>

        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Modificar</button>
        </div>
    </form>

</div>

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/RegistroVisitas/ListaRegistroVisita.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.ListaRegistroVisitaModel
@{
    ViewData["Title"] = "Registro de visitas";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Formulario para el registro de visitas</title>
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="contenedor">
    <header class="header">
        <h1 id="title" class="text-center">Registro de visitas</h1>
        <p id="description" class="description text-center"> Ingresa los datos de la visita.</p>
    </header>

    <form method="post" class="grid2-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.MascotaId">Id de la Mascota</label>
            <input type="number" asp-for="RegistroVisita.MascotaId" name="MascotaId" id="MascotaId" class="form-control" placeholder="Ingrese el id de la mascota">
            <span asp-validation-for="RegistroVisita.MascotaId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.TarjetaProfesionalVeterinario">Veterinario</label>
            <input type="number" asp-for="RegistroVisita.TarjetaProfesionalVeterinario" name="TarjetaProfesionalVeterinario" id="TarjetaProfesionalVeterinario" class="form-control" placeholder="Ingrese la tarjeta profesional">
            <span asp-validation-for="RegistroVisita.TarjetaProfesionalVeterinario" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FechaHora">Fecha de la visita</label>
            <input type="date" asp-for="RegistroVisita.FechaHora" name="FechaHora" id="FechaHora" class="form-control" placeholder="Ingrese la fecha de la visita">
            <span asp-validation-for="RegistroVisita.FechaHora" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Temperatura">Temperatura</label>
            <input type="number" asp-for="RegistroVisita.Temperatura" name="Temperatura" id="Temperatura" class="form-control" placeholder="Ingrese la temperatura">
            <span asp-validation-for="RegistroVisita.Temperatura" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Peso">Peso</label>
            <input type="number" asp-for="RegistroVisita.Peso" name="Peso" id="Peso" class="form-control" placeholder="Ingrese el peso">
            <span asp-validation-for="RegistroVisita.Peso" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FrecuenciaRespiratoria">Frecuencia Respiratoria</label>
            <input type="text" asp-for="RegistroVisita.FrecuenciaRespiratoria" name="FrecuenciaRespiratoria" id="FrecuenciaRespiratoria" class="form-control" placeholder="Ingrese la frecuencia respiratoria">
            <span asp-validation-for="RegistroVisita.FrecuenciaRespiratoria" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.FrecuenciaCardiaca">Frecuencia Cardiaca</label>
            <input type="text" asp-for="RegistroVisita.FrecuenciaCardiaca" name="FrecuenciaCardiaca" id="FrecuenciaCardiaca" class="form-control" placeholder="Ingrese la frecuencia cardiaca">
            <span asp-validation-for="RegistroVisita.FrecuenciaCardiaca" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.EstadoAnimo">Estado de ánimo</label>
            <select type="text" asp-for="RegistroVisita.EstadoAnimo" name="EstadoAnimo" id="EstadoAnimo" class="form-control" required="">
                <option disabled="" selected="" value="">Seleccione el estado de ánimo</option>
                <option value="0">Tranquilo</option>
                <option value="1">Hiperactivo</option>
                <option value="2">Asustado</option>
                <option value="3">Nervioso</option>
                <option value="4">Agresivo</option>
                <option value="5">Triste</option>
                <option value="6">Aislado</option>
                <option value="7">Sin apetito</option>
                <option value="8">Ansioso</option>
                <option value="9">Deprimido</option>
            </select>
            <span asp-validation-for="RegistroVisita.EstadoAnimo" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="RegistroVisita.Medicamentos">Medicamentos</label>
            <input type="text" asp-for="RegistroVisita.Medicamentos" name="Medicamentos" id="Medicamentos" class="form-control" placeholder="Ingrese los medicamentos">
            <span asp-validation-for="RegistroVisita.Medicamentos" class="text-danger"></span>
        </div>

        <div class="form-group-full">
            <label id="label" asp-for="RegistroVisita.Recomendaciones">Recomendaciones</label>
            <textarea type="text-area" asp-for="RegistroVisita.Recomendaciones" name="Recomendaciones" id="Recomendaciones" class="input-textarea" placeholder="Ingrese las recomendaciones aquí...">
            </textarea>
            <span asp-validation-for="RegistroVisita.Recomendaciones" class="text-danger"></span>
        </div>

        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </form>

    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr class="registers">
                <th style="text-align: center;">MascotaId</th>
                <th style="text-align: center;">Veterinario</th>
                <th style="text-align: center;">Fecha Visita</th>
                <th style="text-align: center;">Temperatura (°C)</th>
                <th style="text-align: center;">Peso (Kg)</th>
                <th style="text-align: center;">Frecuencia Respiratoria</th>
                <th style="text-align: center;">Frecuencia Cardiaca</th>
                <th style="text-align: center;">Estado Animo</th>
                <th style="text-align: center;">Medicamentos</th>
                <th style="text-align: center;">Recomendaciones</th>
                <th style="text-align: center;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var RegistroVisita in Model.RegistrosVisitas) {
                
                <tr>
                    <td style="text-align: center;">@RegistroVisita.MascotaId</td>
                    <td style="text-align: center;">@RegistroVisita.TarjetaProfesionalVeterinario</td>
                    <td style="text-align: center;">@RegistroVisita.FechaHora</td>
                    <td style="text-align: center;">@RegistroVisita.Temperatura</td>
                    <td style="text-align: center;">@RegistroVisita.Peso</td>
                    <td style="text-align: center;">@RegistroVisita.FrecuenciaRespiratoria</td>
                    <td style="text-align: center;">@RegistroVisita.FrecuenciaCardiaca</td>
                    <td style="text-align: center;">@RegistroVisita.EstadoAnimo</td>
                    <td style="text-align: center;">@RegistroVisita.Medicamentos</td>
                    <td style="text-align: center;">@RegistroVisita.Recomendaciones</td>
                    <td>
                        <a class="btn btn-primary table-btn" asp-page="./EditarRegistroVisita" asp-route-id="@RegistroVisita.Id">Editar</a>
                        <a class="btn btn-primary table-btn" onclick="return confirm('¿Desea eliminar este registo?')" asp-page-handler="DeleteRegistroVisita" asp-route-id="@RegistroVisita.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    
    @section Scripts { 
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); } 
    }
    
</div>