MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Mascotas/EditarMascota.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;

namespace MascotaFeliz.App.Frontend.Pages
{
    public class EditarMascotaModel : PageModel {
        private readonly IRepositorioMascota _repoMascota;
        
        [BindProperty]
        public Mascota Mascota { get; set;} 

        public EditarMascotaModel (IRepositorioMascota repoMascota) {
            this._repoMascota = repoMascota;
        }
        
        public IActionResult OnGet(int id) {
            Mascota = _repoMascota.GetMascota(id);
                return Page();
        }

        public IActionResult OnPost() {
            Mascota = _repoMascota.UpdateMascota(Mascota);
            return RedirectToPage("./ListaMascota");
        }
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Mascotas/ListaMascota.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;
using System;
using Microsoft.AspNetCore.Authorization;

namespace MascotaFeliz.App.Frontend.Pages {

    [Authorize]
    public class ListaMascotaModel : PageModel {
    
    private readonly IRepositorioMascota _repoMascota;
    public IEnumerable<Mascota> Mascotas { get; set;}
    [BindProperty]
    public Mascota Mascota { get; set;} 

    public ListaMascotaModel (IRepositorioMascota repoMascota) {
        _repoMascota = repoMascota;
    }

        public void OnGet() {
            Mascotas = listarMascotas();
        }

        public ActionResult OnPost() {
            if(!ModelState.IsValid) {
                return RedirectToPage("ListaPropietario");
            }
            AddMascota();
            return RedirectToPage("ListaMascota");
        }

        public IEnumerable<Mascota> listarMascotas() {
            IEnumerable<Mascota> Mascotas = _repoMascota.GetAllMascotas();
            return Mascotas;
        }

        private void AddMascota () {
            
            _repoMascota.AddMascota(new Mascota {
                PropietarioId = Mascota.PropietarioId,
                Nombre = Mascota.Nombre,
                FechaNacimiento = Mascota.FechaNacimiento,
                TipoMascota = Mascota.TipoMascota,
                Raza = Mascota.Raza,
                Sexo = Mascota.Sexo,
                Color = Mascota.Color,
                Afiliado = Mascota.Afiliado
            });
        }

        public IActionResult OnGetDeleteMascota(int Id) {
            _repoMascota.DeleteMascota(Id);
            return Redirect("ListaMascota");
        }
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Mascotas/Registros/ListaRegistros.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;

namespace MascotaFeliz.App.Frontend.Pages
{
    public class ListaRegistrosModel : PageModel {

        private readonly IRepositorioMascota _repoMascota;
        [BindProperty]
        public Mascota Mascota { get; set; }

        public IEnumerable<RegistroVisita> Registros { get; set; }

        public ListaRegistrosModel(IRepositorioMascota repoMascota) {
            _repoMascota = repoMascota;  
        }

        public void OnGet(int? mascotaId) {
            if (mascotaId.HasValue) {
                Mascota = _repoMascota.GetMascota(mascotaId.Value);
            }

            if(Mascota == null) {
                Page();
            }
            else {
                Registros = _repoMascota.GetRegistrosMascota(mascotaId.Value);
            }
        }  
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Mascotas/EditarMascota.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.EditarMascotaModel
@{
    int mascotaId=Model.Mascota.Id;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Formulario para la adición de propietarios</title>
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Actualización de mascotas</h1>
        <p id="description" class="description text-center"> Ingresa los datos de la mascota aquí.</p>
    </header>

    <form method="post" class="grid3-form">
        <input asp-for="Mascota.Id" type="hidden"/>
        
        <div class="form-group">
            <label id="label" asp-for="Mascota.PropietarioId">Id del propietario</label>
            <input type="number" asp-for="Mascota.PropietarioId" name="Mascota.PropietarioId" id="nombre" class="form-control" placeholder="Ingrese el id del propietario">
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Nombre">Nombre</label>
            <input type="text" asp-for="Mascota.Nombre" name="Mascota.Nombre" id="apellido" class="form-control" placeholder="Ingrese el nombre de la mascota">
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.FechaNacimiento">Fecha de Nacimiento</label>
            <input type="date" asp-for="Mascota.FechaNacimiento" name="Mascota.FechaNacimiento" id="fecha-nacimiento" class="form-control" placeholder="">
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.TipoMascota">Tipo</label>
            <select asp-for="Mascota.TipoMascota" name="Mascota.TipoMascota" id="dropdown" class="form-control" required="">
                <option disabled="" value="">Seleccione el tipo de mascota</option>
                <option value="0">Canino</option>
                <option value="1">Felino</option>
                <option value="2">Ave</option>
                <option value="3">Roedor</option>
                <option value="4">Pez</option>
            </select>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Raza">Raza</label>
            <input type="text" asp-for="Mascota.Raza" name="Mascota.Raza" id="raza" class="form-control" placeholder="Ingrese la raza de la mascota">
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Sexo">Sexo</label>
            <select asp-for="Mascota.Sexo" name="Mascota.Sexo" id="dropdown" class="form-control" required="">
                <option disabled="" value="">Selecciona una opción</option>
                <option value="Macho">Macho</option>
                <option value="Hembra">Hembra</option>
            </select>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Color">Color</label>
            <input type="text" asp-for="Mascota.Color" name="Mascota.Color" id="color" class="form-control" placeholder="Ingrese el color de la mascota">
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Afiliado">Afiliado</label>
            <input type="text" asp-for="Mascota.Afiliado" name="Mascota.Afiliado" id="afiliado" class="form-control" placeholder="Ingrese 'True' o  'False'">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Modificar</button>
            <a class="btn btn-primary table-btn" asp-page="./Registros/ListaRegistros" asp-route-mascotaId="@mascotaId">Registros</a>
        </div>

    </form>

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Mascotas/ListaMascota.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.ListaMascotaModel
@{
    ViewData["Title"] = "Mascotas";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Formulario para la adición de propietarios</title>
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="contenedor">
    <header class="header">
        <h1 id="title" class="text-center">Adición de mascotas</h1>
        <p id="description" class="description text-center"> Ingresa los datos de la mascota aquí.</p>
    </header>

    <form method="post" class="grid3-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label id="label" asp-for="Mascota.PropietarioId">Id del propietario</label>
            <input type="number" asp-for="Mascota.PropietarioId" name="Mascota.PropietarioId" id="nombre" class="form-control" placeholder="Ingrese el id del propietario">
            <span asp-validation-for="Mascota.PropietarioId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Nombre">Nombre</label>
            <input type="text" asp-for="Mascota.Nombre" name="Mascota.Nombre" id="apellido" class="form-control" placeholder="Ingrese el nombre de la mascota">
            <span asp-validation-for="Mascota.Nombre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.FechaNacimiento">Fecha de Nacimiento</label>
            <input type="date" asp-for="Mascota.FechaNacimiento" name="Mascota.FechaNacimiento" id="fecha-nacimiento" class="form-control" placeholder="">
            <span asp-validation-for="Mascota.FechaNacimiento" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.TipoMascota">Tipo</label>
            <select asp-for="Mascota.TipoMascota" name="Mascota.TipoMascota" id="dropdown" class="form-control" required="">
                <option disabled="" selected="" value="">Seleccione el tipo de mascota</option>
                <option value="0">Canino</option>
                <option value="1">Felino</option>
                <option value="2">Ave</option>
                <option value="3">Roedor</option>
                <option value="4">Pez</option>
            </select>
            <span asp-validation-for="Mascota.TipoMascota" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Raza">Raza</label>
            <input type="text" asp-for="Mascota.Raza" name="Mascota.Raza" id="raza" class="form-control" placeholder="Ingrese la raza de la mascota">
            <span asp-validation-for="Mascota.Raza" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Sexo">Sexo</label>
            <select asp-for="Mascota.Sexo" name="Mascota.Sexo" id="dropdown" class="form-control" required="">
                <option disabled="" selected="" value="">Selecciona una opción</option>
                <option value="Macho">Macho</option>
                <option value="Hembra">Hembra</option>
            </select>
            <span asp-validation-for="Mascota.Sexo" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Color">Color</label>
            <input type="text" asp-for="Mascota.Color" name="Mascota.Color" id="color" class="form-control" placeholder="Ingrese el color de la mascota">
            <span asp-validation-for="Mascota.Color" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Mascota.Afiliado">Afiliado</label>
            <input type="text" asp-for="Mascota.Afiliado" name="Mascota.Afiliado" id="afiliado" class="form-control" placeholder="Ingrese 'True' o  'False'">
            <span asp-validation-for="Mascota.Afiliado" class="text-danger"></span>
        </div>

        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </form>

    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th style="text-align: center;">Id</th>
                <th style="text-align: center;">PropietarioId</th>
                <th style="text-align: center;">Nombre</th>
                <th style="text-align: center;">Fecha Nacimiento</th>
                <th style="text-align: center;">Tipo Mascota</th>
                <th style="text-align: center;">Raza</th>
                <th style="text-align: center;">Sexo</th>
                <th style="text-align: center;">Color</th>
                <th style="text-align: center;">Afiliado</th>
                <th style="text-align: center;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var Mascota in Model.Mascotas) {
                
                <tr>
                    <td style="text-align: center;">@Mascota.Id</td>
                    <td style="text-align: center;">@Mascota.PropietarioId</td>
                    <td style="text-align: center;">@Mascota.Nombre</td>
                    <td style="text-align: center;">@Mascota.FechaNacimiento</td>
                    <td style="text-align: center;">@Mascota.TipoMascota</td>
                    <td style="text-align: center;">@Mascota.Raza</td>
                    <td style="text-align: center;">@Mascota.Sexo</td>
                    <td style="text-align: center;">@Mascota.Color</td>
                    <td style="text-align: center;">@Mascota.Afiliado</td>
                    <td>
                        <a class="btn btn-primary table-btn" asp-page="./EditarMascota" asp-route-id="@Mascota.Id">Editar</a>
                        <a class="btn btn-primary table-btn" onclick="return confirm('¿Desea eliminar este registo?')" asp-page-handler="DeleteMascota" asp-route-id="@Mascota.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    @section Scripts { 
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); } 
    }
    
</div>