MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Propietarios/EditarPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;

namespace MascotaFeliz.App.Frontend.Pages
{
    public class EditarPropietarioModel : PageModel {

        private readonly IRepositorioPropietario _repoPropietario;
        
        [BindProperty]
        public Propietario Propietario { get; set;} 

        public EditarPropietarioModel (IRepositorioPropietario repoPropietario) {
            this._repoPropietario = repoPropietario;
        }
        
        public IActionResult OnGet(int id) {
            Propietario = _repoPropietario.GetPropietario(id);
                return Page();
        }

        public IActionResult OnPost() {
            Propietario = _repoPropietario.UpdatePropietario(Propietario);
            return RedirectToPage("./ListaPropietario");
        }
    }        
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Propietarios/ListaPropietario.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MascotaFeliz.App.Dominio;
using MascotaFeliz.App.Persistencia;
using Microsoft.AspNetCore.Authorization;

namespace MascotaFeliz.App.Frontend.Pages {

    [Authorize]
    public class ListaPropietarioModel : PageModel {
    
    private readonly IRepositorioPropietario _repoPropietario;
    public IEnumerable<Propietario> Propietarios { get; set;}
    [BindProperty]
    public Propietario Propietario { get; set;} 

    public ListaPropietarioModel (IRepositorioPropietario repoPropietario) {
        _repoPropietario = repoPropietario;
    }

        public void OnGet() {
            Propietarios = listarPropietarios();
        }

        public ActionResult OnPost() {
            if(!ModelState.IsValid) {
                return RedirectToPage("ListaPropietario");
            }
            AddPropietario();
            return RedirectToPage("ListaPropietario");
        }

        public IEnumerable<Propietario> listarPropietarios() {
            IEnumerable<Propietario> Propietarios = _repoPropietario.GetAllPropietarios();
            return Propietarios;
        }

        private void AddPropietario () {

            _repoPropietario.AddPropietario(new Propietario {
                Cedula = Propietario.Cedula,
                Nombre = Propietario.Nombre,
                Apellido = Propietario.Apellido,
                NumeroTelefono = Propietario.NumeroTelefono,
                Direccion = Propietario.Direccion,
                Email = Propietario.Email
            });
        }

        public IActionResult OnGetDeletePropietario(int Id) {
            _repoPropietario.DeletePropietario(Id);
            return Redirect("ListaPropietario");
        }
    }
}

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Propietarios/EditarPropietario.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.EditarPropietarioModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Formulario para la modificación de propietarios</title>
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Actualización de propietarios</h1>
        <p id="description" class="description text-center">Modifica los datos del propietario aquí.</p>
    </header>

    <form method="post" class="survey-form">
        <input asp-for="Propietario.Id" type="hidden"/>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Nombre" class="control-label">Nombre</label>
            <input asp-for="Propietario.Nombre" id="nombre" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Apellido" class="control-label">Apellido</label>
            <input asp-for="Propietario.Apellido" id="apellido" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Cedula" class="control-label">Cedula</label>
            <input asp-for="Propietario.Cedula" id="cedula" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.NumeroTelefono" class="control-label">Número Teléfono</label>
            <input asp-for="Propietario.NumeroTelefono" id="telefono" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Direccion" class="control-label">Dirección</label>
            <input asp-for="Propietario.Direccion" id="direccion" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Email" class="control-label">Email</label>
            <input asp-for="Propietario.Email" id="email" class="form-control"/>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Modificar</button>
        </div>
    </form>

</div>

MascotaFeliz.App/MascotaFeliz.App.Frontend/Pages/Propietarios/ListaPropietario.cshtml
@page
@model MascotaFeliz.App.Frontend.Pages.ListaPropietarioModel
@{
    ViewData["Title"] = "Propietarios";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Formulario para la adición de propietarios</title>
    <link rel="stylesheet" href="~/css/properties.css" />
</head>

<div class="contenedor">
    <header class="header">
        <h1 id="title" class="text-center">Adición de propietarios</h1>
        <p id="description" class="description text-center"> Ingresa los datos del propietario aquí.</p>
    </header>

    <form method="post" class="survey-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label id="label" asp-for="Propietario.Nombre">Nombre</label>
            <input type="text" asp-for="Propietario.Nombre" name="Propietario.Nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre">
            <span asp-validation-for="Propietario.Nombre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Apellido">Apellido</label>
            <input type="text" asp-for="Propietario.Apellido" name="Propietario.Apellido" id="apellido" class="form-control" placeholder="Ingrese el apellido">
            <span asp-validation-for="Propietario.Apellido" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Cedula">Cédula</label>
            <input type="text" asp-for="Propietario.Cedula" name="Propietario.Cedula" id="cedula" class="form-control" placeholder="Ingrese la cédula">
            <span asp-validation-for="Propietario.Cedula" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.NumeroTelefono">Número Teléfono</label>
            <input type="text" asp-for="Propietario.NumeroTelefono" name="Propietario.NumeroTelefono" id="telefono" class="form-control" placeholder="Ingrese el número de teléfono">
            <span asp-validation-for="Propietario.NumeroTelefono" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Direccion">Dirección</label>
            <input type="text" asp-for="Propietario.Direccion" name="Propietario.Direccion" id="direccion" class="form-control" placeholder="Ingrese la dirección">
            <span asp-validation-for="Propietario.Direccion" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label id="label" asp-for="Propietario.Email">Email</label>
            <input type="email" asp-for="Propietario.Email" name="Propietario.Email" id="email" class="form-control" placeholder="Ingrese el email">
            <span asp-validation-for="Propietario.Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </form>

    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th style="text-align: center;">Id</th>
                <th style="text-align: center;">Cédula</th>
                <th style="text-align: center;">Nombre</th>
                <th style="text-align: center;">Apellido</th>
                <th style="text-align: center;">Número Teléfono</th>
                <th style="text-align: center;">Dirección</th>
                <th style="text-align: center;">Email</th>
                <th style="text-align: center;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var Propietario in Model.Propietarios) {
                
                <tr>
                    <td style="text-align: center;">@Propietario.Id</td>
                    <td style="text-align: center;">@Propietario.Cedula</td>
                    <td style="text-align: center;">@Propietario.Nombre</td>
                    <td style="text-align: center;">@Propietario.Apellido</td>
                    <td style="text-align: center;">@Propietario.NumeroTelefono</td>
                    <td style="text-align: center;">@Propietario.Direccion</td>
                    <td style="text-align: center;">@Propietario.Email</td>
                    <td>
                        <a class="btn btn-primary table-btn" asp-page="./EditarPropietario" asp-route-id="@Propietario.Id">Editar</a>
                        <a class="btn btn-primary table-btn" onclick="return confirm('¿Desea eliminar este registo?')" asp-page-handler="DeletePropietario" asp-route-id="@Propietario.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    @section Scripts { 
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); } 
    }
    
</div>